server:
  port: 9000

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: discover-service
  security:
    user:
      name: admin
      password: admin2580

eureka:
  instance:
    hostname: 141.164.61.114
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/
